// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {common} from '../models';

export function GetNetworkDetails():Promise<Array<main.NetworkDetails>>;

export function GetReportPath():Promise<string>;

export function GetSecurityFindings():Promise<main.SecurityFindings>;

export function RunLayerTests(arg1:Array<number>):Promise<Array<common.TestResult>>;

export function ScanPorts():Promise<Array<main.PortInfo>>;
