// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetNetworkDetails() {
  return window['go']['main']['App']['GetNetworkDetails']();
}

export function GetReportPath() {
  return window['go']['main']['App']['GetReportPath']();
}

export function GetSecurityFindings() {
  return window['go']['main']['App']['GetSecurityFindings']();
}

export function RunLayerTests(arg1) {
  return window['go']['main']['App']['RunLayerTests'](arg1);
}

export function ScanPorts() {
  return window['go']['main']['App']['ScanPorts']();
}
